spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root
    hikari:
      schema: public
  driverClassName: org.postgresql.Driver

  sql:
    init:
      mode: always



logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
          JpaTransactionManager: DEBUG

        transaction:
          interceptor: TRACE
