version: '3'
services:
  postgres:
    image: postgres:14-alpine3.14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql