CREATE TABLE IF NOT EXISTS contacts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,
    first_name VARCHAR(256) NOT NULl,
    last_name  VARCHAR(256) NOT NULL,
    email      VARCHAR(256) NOT NULL
        UNIQUE,
    phone_number      VARCHAR(256) NOT NULL
        UNIQUE
);

insert into contacts (first_name, last_name, email, phone_number) values ('Ursula', 'Jeschner', 'ujeschner0@amazon.de', '+86 (201) 386-9727');
insert into contacts (first_name, last_name, email, phone_number) values ('Pauly', 'Tulip', 'ptulip1@microsoft.com', '+52 (481) 123-0214');
insert into contacts (first_name, last_name, email, phone_number) values ('Quinlan', 'Dailly', 'qdailly2@unblog.fr', '+86 (972) 302-2263');
insert into contacts (first_name, last_name, email, phone_number) values ('Robbi', 'Stolte', 'rstolte3@vk.com', '+86 (932) 238-6782');
insert into contacts (first_name, last_name, email, phone_number) values ('Katya', 'Castille', 'kcastille4@ucsd.edu', '+351 (137) 260-2726');
insert into contacts (first_name, last_name, email, phone_number) values ('Concettina', 'Jefford', 'cjefford5@barnesandnoble.com', '+81 (251) 855-5144');
insert into contacts (first_name, last_name, email, phone_number) values ('Timothee', 'Ovitts', 'tovitts6@seattletimes.com', '+1 (144) 603-5120');
insert into contacts (first_name, last_name, email, phone_number) values ('Arnie', 'Ropking', 'aropking7@yandex.ru', '+386 (213) 143-1137');
insert into contacts (first_name, last_name, email, phone_number) values ('Starlin', 'Fendley', 'sfendley8@bravesites.com', '+46 (728) 919-6670');
insert into contacts (first_name, last_name, email, phone_number) values ('Theodora', 'Pirdy', 'tpirdy9@vk.com', '+351 (248) 307-6714');